#QUES2
USE CUSTOMER_DB;
#DROP PROCEDURE NAMES_;
#SELECT * FROM customer;
DELIMITER $$
CREATE PROCEDURE NAMES_
(
IN CITY NVARCHAR(30)
)
BEGIN
#SELECT * FROM customer;
SELECT CUST_NAME FROM CUSTOMER_DB.customer where WORKING_AREA=CITY;
END$$
DELIMITER ;
CALL NAMES_("Bangalore");
