#QUES3
USE CUSTOMER_DB;
#DROP PROCEDURE NAMES_GRADES;
#SELECT * FROM customer;
DELIMITER $$
CREATE PROCEDURE NAMES_GRADES()
BEGIN
#SELECT * FROM customer;
#SELECT CUST_NAME,GRADE FROM CUSTOMER_DB.customer;
SELECT CUST_NAME ,GRADE FROM CUSTOMER_DB.customer where OPENING_AMT+RECEIVE_AMT > 10000;
END$$
DELIMITER ;
CALL NAMES_GRADES();
