#QUES4
USE CUSTOMER_DB;
#DROP PROCEDURE AGENT;
DELIMITER $$

CREATE PROCEDURE AGENT()
   BEGIN
      DECLARE done INT DEFAULT 0;
      DECLARE GRADE_ decimal(10,0);
      DECLARE NAME_, CITY_, COUNTRY_ NVARCHAR(100);
      DECLARE cur CURSOR FOR SELECT CUST_NAME,CUST_CITY,CUST_COUNTRY,GRADE FROM customer WHERE AGENT_CODE LIKE 'A00%';
      DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
      OPEN cur;
      label: LOOP
      FETCH cur INTO NAME_, CITY_, COUNTRY_, GRADE_;
      
     # INSERT INTO BACKUP_ VALUES(NAME_,CITY_,COUNTRY_,GRADE_);
      IF done = 1 THEN LEAVE label;
      END IF;
      SELECT NAME_, CITY_, COUNTRY_, GRADE_;
      END LOOP;
      CLOSE cur;
   END$$
DELIMITER ;
CALL AGENT();
