SELECT * FROM (SELECT DNUMBER,DNAME FROM DEPARTMENT JOIN (SELECT ESSN,COUNT(*) FROM DEPENDENT WHERE SEX='F' GROUP BY ESSN HAVING COUNT(*)>=2) 
AS T ON DEPARTMENT.MGR_SSN=T.ESSN) AS T1 NATURAL JOIN (SELECT DNUMBER,COUNT(*) FROM DEPT_LOCATIONS GROUP BY DNUMBER) AS T2 ;
