SELECT CONCAT(EMPLOYEE.FNAME, ' ',EMPLOYEE.LNAME) AS FULL_NAME, EMPLOYEE.SSN, DEPARTMENT.DNUMBER, DEPARTMENT.DNAME FROM DEPARTMENT JOIN EMPLOYEE ON DEPARTMENT.MGR_SSN=EMPLOYEE.SSN WHERE 
EMPLOYEE.SSN=(SELECT EMPLOYEE.SUPER_SSN FROM EMPLOYEE JOIN (SELECT SUM(HOURS),ESSN FROM WORKS_ON GROUP BY ESSN HAVING SUM(HOURS)<40) AS T ON T.ESSN=EMPLOYEE.SSN);
