SELECT * FROM 
(SELECT MGR_SSN,DNUMBER FROM DEPARTMENT NATURAL JOIN (SELECT DNUMBER,COUNT(*) AS LOCATIONS FROM DEPT_LOCATIONS GROUP BY DNUMBER HAVING COUNT(*)>=2)AS T) AS T2 
NATURAL JOIN 
(SELECT ESSN AS MGR_SSN,COUNT(*) AS DEPENDENTS FROM DEPENDENT GROUP BY ESSN) AS T3 ;
